name: Compilar Kernel Vayu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar código fuente
        uses: actions/checkout@v4

      - name: Compilar Kernel Android
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: '.'
          kernel-dir: '.'
          config: vayu_defconfig
          arch: arm64
          other-clang-url: https://github.com/kdrag0n/proton-clang/archive/refs/heads/master.tar.gz
          other-gcc32-url: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/heads/android12L-release.tar.gz
          aosp-gcc: false
          disable-lto: true
          anykernel3: true
          ksu: false
