name: Compilar Kernel Vayu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compilar Kernel Android
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/lagartorojas/android_kernel_xiaomi_vayu
          kernel-branch: cyf
          config: vayu_user_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          disable-lto: true
          anykernel3: true
          ksu: false
